name: TaleEnd
version: '${project.version}'
main: com.erydevs.TaleEnd
author: Agent1k
api-version: '1.16'
softdepend: [ PlaceholderAPI ]
commands:
  end:
permissions:
  end.admin:
    default: op
  end.portal:
    default: op